micronaut:
  application:
    name: todobackend
  server:
    cors:
      enabled: true
jackson:
  serializationInclusion: ALWAYS
datasources:
  default:
    url: "jdbc:mysql:///todo?\
      cloudSqlInstance=cloud-run-book:europe-west1:sql-db&\
      socketFactory=com.google.cloud.sql.mysql.SocketFactory&\
      useSSL=false"
    username: root
    driverClassName: com.mysql.cj.jdbc.Driver
    minimumIdle: 1
    maximumPoolSize: 1
    schema-generate: CREATE
    dialect: MYSQL
