micronaut:
  application:
    name: todobackend
  server:
    cors:
      enabled: true
jackson:
  serializationInclusion: ALWAYS
datasources:
  default:
    url: jdbc:mysql:///todo?cloudSqlInstance=wv-chapter-3:europe-west1:sql-db&socketFactory=com.google.cloud.sql.mysql.SocketFactory&useSSL=false
    username: root
#    password: secret
    driverClass: com.mysql.cj.jdbc.Driver
    minimumIdle: 1
    maximumPoolSize: 1
    schema-generate: CREATE
    dialect: MYSQL